---
name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Web base layers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get env file from droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".env"
          target: /root/apps/reddex
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-to: type=gha,mode=max
          secrets: |
            "FONTAWESOME_NPM_AUTH_TOKEN=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
  build-web:
    needs: [prepare]
    name: app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/reddex:${{ inputs.tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/reddex
          cache-from: type=gha
          cache-to: type=gha,mode=max
