---
name: "Deploy to prod"

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Add PR number for tagging"
        type: string
        required: true
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true || inputs.deploy == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote Reddex to latest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/reddex/app:latest \
            ghcr.io/${{ github.repository_owner }}/reddex/app:pr-${{ github.event.pull_request.number }}

      - name: Deploy docker images to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd apps
            cd reddex
            git checkout main
            git pull
            cd ../
            docker compose pull ghcr.io/${{ github.repository_owner }}/reddex/app:latest 
            docker compose down reddex-client
            docker compose up reddex-client -d
