---
name: "Deploy to prod"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  deploy:
    needs: [build-web]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote Reddex to latest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/reddex \
            ghcr.io/${{ github.repository_owner }}/reddex

      - name: Deploy docker images to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd apps
            docker compose pull ghcr.io/${{ github.repository_owner }}/reddex 
            docker compose down reddex-client
            docker compose up reddex-client -d
